### ISSUE TITLE
Kanban Board Review

### ISSUE THREAD

**Issue by vechicin** [qwibbler/RubyCapstone-Catalogue#27]
# There are three people working on this project, they are: 

- Humaira Zaman (Team 1): @qwibbler
- Santiago Velosa (Team 2): @vechicin 
- Shady Shawkat (Team 3): @ShadyShawkat 

This is the [link](https://github.com/qwibbler/RubyCapstone-Catalogue/projects/1) to the Kanban board

**Comment by julie-ify** [comment]
Hi @vechicin, @ShadyShawkat and @qwibbler, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
